In [2]:
%matplotlib inline
# import sys
# reload(sys)
# sys.setdefaultencoding('utf8')
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import statsmodels.api as sm
import matplotlib.pyplot as plt
import scipy.stats as stats
import random as rnd
import plotly
from sklearn.metrics import classification_report, confusion_matrix
plotly.tools.set_credentials_file(username='prdpram08', api_key='pPtrb0GSvQZ7yO5EoODO')
import plotly.plotly as py
from plotly.graph_objs import *
import string
import plotly.graph_objs as go
import cufflinks as cf
from sklearn.cross_validation import train_test_split
from sklearn.linear_model import LassoLarsCV
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.options.display.max_colwidth = 500
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier
train_df = pd.read_csv("fordTrain.csv")
test_df = pd.read_csv("fordTest.csv")
solution_df = pd.read_csv("Solution.csv")

/Users/pradeep/anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning:

This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.



In [3]:
train_df.head()

TrialID  ObsNum  IsAlert       P1        P2    P3       P4        P5   P6  \
0        0       0        0  34.7406   9.84593  1400  42.8571  0.290601  572   
1        0       1        0  34.4215  13.41120  1400  42.8571  0.290601  572   
2        0       2        0  34.3447  15.18520  1400  42.8571  0.290601  576   
3        0       3        0  34.3421   8.84696  1400  42.8571  0.290601  576   
4        0       4        0  34.3322  14.69940  1400  42.8571  0.290601  576   

        P7  P8   E1   E2  E3  E4        E5   E6  E7  E8  E9  E10  E11      V1  \
0  104.895   0  0.0  0.0   1 -20  0.015875  324   1   1   1   57  0.0  101.96   
1  104.895   0  0.0  0.0   1 -20  0.015875  324   1   1   1   57  0.0  101.98   
2  104.167   0  0.0  0.0   1 -20  0.015875  324   1   1   1   57  0.0  101.97   
3  104.167   0  0.0  0.0   1 -20  0.015875  324   1   1   1   57  0.0  101.99   
4  104.167   0  0.0  0.0   1 -20  0.015875  324   1   1   1   57  0.0  102.07   

      V2   V3       V4  V5    V6  V7    V8  V9  V10      V11  
0  0.175  752  5.99375   0  2005   0  13.4   0    4  14.8004  
1  0.455  752  5.99375   0  2007   0  13.4   0    4  14.7729  
2  0.280  752  5.99375   0  2011   0  13.4   0    4  14.7736  
3  0.070  752  5.99375   0  2015   0  13.4   0    4  14.7667  
4  0.175  752  5.99375   0  2017   0  13.4   0    4  14.7757

In [4]:
train_df.describe()

TrialID         ObsNum        IsAlert             P1  \
count  604329.000000  604329.000000  604329.000000  604329.000000   
mean      250.167657     603.841765       0.578799      35.449020   
std       145.446164     348.931601       0.493752       7.484629   
min         0.000000       0.000000       0.000000     -22.481200   
25%       125.000000     302.000000       0.000000      31.758100   
50%       250.000000     604.000000       1.000000      34.145100   
75%       374.000000     906.000000       1.000000      37.311900   
max       510.000000    1210.000000       1.000000     101.351000   

                  P2             P3             P4             P5  \
count  604329.000000  604329.000000  604329.000000  604329.000000   
mean       11.996525    1026.671035      64.061965       0.178923   
std         3.760292     309.277877      19.755950       0.372309   
min       -45.629200     504.000000      23.885300       0.038920   
25%         9.903540     792.000000      49.180300       0.092110   
50%        11.400400    1000.000000      60.000000       0.105083   
75%        13.644200    1220.000000      75.757600       0.138814   
max        71.173700    2512.000000     119.048000      27.202200   

                  P6             P7        P8             E1             E2  \
count  604329.000000  604329.000000  604329.0  604329.000000  604329.000000   
mean      845.384610      77.887628       0.0      10.512332     102.790045   
std      2505.335141      18.577930       0.0      14.049071     127.258629   
min       128.000000       0.262224       0.0       0.000000       0.000000   
25%       668.000000      66.666700       0.0       0.000000       0.000000   
50%       800.000000      75.000000       0.0       0.000000       0.000000   
75%       900.000000      89.820400       0.0      28.240000     211.584000   
max    228812.000000     468.750000       0.0     243.991000     359.995000   

                  E3             E4             E5             E6  \
count  604329.000000  604329.000000  604329.000000  604329.000000   
mean        0.290565      -4.230136       0.016262     358.674738   
std         1.006162      35.508596       0.002304      27.399973   
min         0.000000    -250.000000       0.008000     260.000000   
25%         0.000000      -8.000000       0.015686     348.000000   
50%         0.000000       0.000000       0.016001     365.000000   
75%         0.000000       6.000000       0.016694     367.000000   
max         4.000000     260.000000       0.023939     513.000000   

                  E7             E8             E9            E10  \
count  604329.000000  604329.000000  604329.000000  604329.000000   
mean        1.757296       1.383058       0.876787      63.311256   
std         2.854852       1.608807       0.328681      18.891029   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       0.000000       1.000000      52.000000   
50%         1.000000       1.000000       1.000000      67.000000   
75%         2.000000       2.000000       1.000000      73.000000   
max        25.000000       9.000000       1.000000     127.000000   

                 E11             V1             V2             V3  \
count  604329.000000  604329.000000  604329.000000  604329.000000   
mean        1.315265      76.965412      -0.037710     573.786433   
std         5.247204      44.387031       0.403896     298.412888   
min         0.000000       0.000000      -4.795000     240.000000   
25%         0.000000      41.930000      -0.175000     255.000000   
50%         0.000000     100.400000       0.000000     511.000000   
75%         0.000000     108.500000       0.070000     767.000000   
max        52.400000     129.700000       3.990000    1023.000000   

                  V4             V5             V6        V7             V8  \
count  604329.000000  604329.000000  604329.000000  604329.0  604329.000000   
mean       19.961030       0.1798

In [5]:
test_df.describe()

TrialID         ObsNum             P1             P2  \
count  120840.000000  120840.000000  120840.000000  120840.000000   
mean       49.496491     603.711635      35.450222      12.008451   
std        28.865733     348.856410       3.303869       4.351161   
min         0.000000       0.000000      17.776300     -25.911800   
25%        24.000000     302.000000      33.456300       9.600658   
50%        49.000000     604.000000      34.877800      11.288900   
75%        74.000000     906.000000      36.862200      13.542925   
max        99.000000    1210.000000      81.819600      39.757300   

                  P3             P4             P5             P6  \
count  120840.000000  120840.000000  120840.000000  120840.000000   
mean     1026.668355      64.148812       0.122339     707.701456   
std       310.874514      19.995102       0.113811      90.398496   
min       504.000000      25.996500       0.040217     468.000000   
25%       788.000000      49.180300       0.089515     636.000000   
50%      1000.000000      60.000000       0.101191     700.000000   
75%      1220.000000      76.142100       0.115462     780.000000   
max      2308.000000     119.048000       4.667770    1216.000000   

                  P7        P8             E1             E2             E3  \
count  120840.000000  120840.0  120840.000000  120840.000000  120840.000000   
mean       86.174020       0.0      10.648237      98.202840       0.191154   
std        11.024309       0.0      13.950893     125.644623       0.776454   
min        49.342100       0.0       0.000000       0.000000       0.000000   
25%        76.923100       0.0       0.000000       0.000000       0.000000   
50%        85.714300       0.0       0.000000       0.000000       0.000000   
75%        94.339600       0.0      28.541000     211.328000       0.000000   
max       128.205000       0.0      64.693000     359.999000       4.000000   

                  E4             E5             E6             E7  \
count  120840.000000  120840.000000  120840.000000  120840.000000   
mean       -0.572095       0.015950     347.686395       1.358284   
std        26.663652       0.002584      47.971289       2.376400   
min      -250.000000       0.008000     260.000000       0.000000   
25%        -6.000000       0.014804     303.000000       0.000000   
50%         0.000000       0.015875     356.000000       1.000000   
75%         6.000000       0.017387     367.000000       2.000000   
max       254.000000       0.023939     513.000000      25.000000   

                  E8             E9            E10            E11  \
count  120840.000000  120840.000000  120840.000000  120840.000000   
mean        1.614176       0.868032      68.655238       1.770682   
std         1.537636       0.338457      17.456849       6.030855   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       1.000000      65.000000       0.000000   
50%         2.000000       1.000000      71.000000       0.000000   
75%         3.000000       1.000000      77.000000       0.000000   
max         9.000000       1.000000     127.000000      36.800000   

                  V1             V2             V3             V4  \
count  120840.000000  120840.000000  120840.000000  120840.000000   
mean       78.696121      -0.036024     562.097443      32.215433   
std        42.534170       0.392249     300.358571      97.893439   
min         0.000000      -3.605000     240.000000       0.000000   
25%        56.540000      -0.175000     255.000000       1.487500   
50%       101.800000       0.000000     497.000000       3.018750   
75%       107.650000       0.070000     767.000000       5.993750   
max       122.650000       3.115000    1023.000000     478.494000   

                  V5             V6        V7             V8        V9  \
count  120840.000000  120840.000000  120840.0  120840.000000  120840.0   
mean        0.179394    1732.128037       0

In [6]:
q=35000
p=15000
train=train_df.head(q)
test=test_df.head(p)

In [7]:
X_train = train.drop(["TrialID","ObsNum","IsAlert"], axis=1)
Y_train = train["IsAlert"]
X_test  = test.drop(["TrialID","ObsNum","IsAlert"], axis=1).copy()
#_test  = test_df.drop(["TrialID","ObsNum"], axis=1)
X_train.shape, Y_train.shape, X_test.shape

((35000, 30), (35000,), (15000, 30))

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train= sc.fit_transform(X_train) 
X_test = sc.transform(X_test)  

In [23]:
logreg = LogisticRegression()
logreg.fit(X_train, Y_train)
Y_pred = logreg.predict(X_test)
acc_log = round(logreg.score(X_train, Y_train) * 100, 2)
print acc_log
print(classification_report(solution_df['Prediction'].head(p), Y_pred))
print(confusion_matrix(solution_df['Prediction'].head(p), Y_pred))

94.8
             precision    recall  f1-score   support

          0       0.98      0.15      0.26      7682
          1       0.53      1.00      0.69      7318

avg / total       0.76      0.56      0.47     15000

[[1138 6544]
 [  22 7296]]


In [10]:
coeff_df = pd.DataFrame(train_df.columns.delete([0,1,2]))
coeff_df.columns = ['Feature']
coeff_df["Correlation"] = pd.Series(logreg.coef_[0])
coeff_df.sort_values(by='Correlation', ascending=False)

Feature  Correlation
16      E9     1.808417
22      V4     0.697323
10      E3     0.348561
20      V2     0.279975
24      V6     0.270323
8       E1     0.247656
3       P4     0.142421
0       P1     0.126302
2       P3     0.068714
18     E11     0.065247
23      V5     0.042646
26      V8     0.032230
21      V3     0.020324
1       P2     0.017463
7       P8     0.000000
27      V9     0.000000
25      V7     0.000000
6       P7    -0.079343
29     V11    -0.082417
12      E5    -0.088859
5       P6    -0.102004
11      E4    -0.135591
28     V10    -0.138710
13      E6    -0.151069
9       E2    -0.317281
15      E8    -0.555571
4       P5    -0.597820
17     E10    -0.721596
19      V1    -1.146053
14      E7    -1.862896

In [11]:
svc = SVC()
svc.fit(X_train, Y_train)
Y_pred = svc.predict(X_test)
acc_svc = round(svc.score(X_train, Y_train) * 100, 2)
print acc_svc
print(classification_report(solution_df['Prediction'].head(p), Y_pred))
print(confusion_matrix(solution_df['Prediction'].head(p), Y_pred))


95.13
             precision    recall  f1-score   support

          0       0.92      0.02      0.05      7682
          1       0.49      1.00      0.66      7318

avg / total       0.71      0.50      0.35     15000

[[ 191 7491]
 [  16 7302]]


In [12]:
knn = KNeighborsClassifier(n_neighbors = 4)
knn.fit(X_train, Y_train)
Y_pred = knn.predict(X_test)
acc_knn = round(knn.score(X_train, Y_train) * 100, 2)
print acc_knn
print(classification_report(solution_df['Prediction'].head(p), Y_pred))
print(confusion_matrix(solution_df['Prediction'].head(p), Y_pred))


97.94
             precision    recall  f1-score   support

          0       0.78      0.13      0.22      7682
          1       0.51      0.96      0.67      7318

avg / total       0.65      0.54      0.44     15000

[[1010 6672]
 [ 286 7032]]


In [13]:
# DT = DecisionTreeClassifier()
# DT.fit(X_train, Y_train)
# Y_pred = DT.predict(X_test)
# DT_score = DT.score(X_train, Y_train)
# print("Decision Tree accuracy score = {:.2f}".format(DT_score*100))
# print(classification_report(solution_df['Prediction'].head(p), Y_pred))
# print(confusion_matrix(solution_df['Prediction'].head(p), Y_pred))


In [14]:
decision_tree = DecisionTreeClassifier()
decision_tree.fit(X_train, Y_train)
Y_pred = decision_tree.predict(X_test)
acc_decision_tree = round(decision_tree.score(X_train, Y_train) * 100, 2)
print acc_decision_tree
print(classification_report(solution_df['Prediction'].head(p), Y_pred))
print(confusion_matrix(solution_df['Prediction'].head(p), Y_pred))


100.0
             precision    recall  f1-score   support

          0       0.58      0.20      0.30      7682
          1       0.50      0.85      0.63      7318

avg / total       0.54      0.52      0.46     15000

[[1526 6156]
 [1112 6206]]


In [15]:
#random_forest= RandomForestClassifier(n_estimators = 100, oob_score = True, n_jobs = -1,random_state =50,max_features = "auto", min_samples_leaf = 50)
random_forest = RandomForestClassifier(n_estimators=100,max_features = "auto",criterion='gini')
random_forest.fit(X_train, Y_train)
Y_pred = random_forest.predict(X_test)
random_forest.score(X_train, Y_train)
acc_random_forest = round(random_forest.score(X_train, Y_train) * 100, 2)
print acc_random_forest
print(classification_report(solution_df['Prediction'].head(p), Y_pred))
print(confusion_matrix(solution_df['Prediction'].head(p), Y_pred))

100.0
             precision    recall  f1-score   support

          0       0.98      0.15      0.26      7682
          1       0.53      1.00      0.69      7318

avg / total       0.76      0.56      0.47     15000

[[1158 6524]
 [  20 7298]]


In [16]:
sgd = SGDClassifier()
sgd.fit(X_train, Y_train)
Y_pred = sgd.predict(X_test)
acc_sgd = round(sgd.score(X_train, Y_train) * 100, 2)
print acc_sgd
print(classification_report(solution_df['Prediction'].head(p), Y_pred))
print(confusion_matrix(solution_df['Prediction'].head(p), Y_pred))

94.27
             precision    recall  f1-score   support

          0       0.85      0.16      0.27      7682
          1       0.52      0.97      0.68      7318

avg / total       0.69      0.56      0.47     15000

[[1222 6460]
 [ 208 7110]]


In [17]:
linear_svc = LinearSVC()
linear_svc.fit(X_train, Y_train)
Y_pred = linear_svc.predict(X_test)
acc_linear_svc = round(linear_svc.score(X_train, Y_train) * 100, 2)
print acc_linear_svc
print(classification_report(solution_df['Prediction'].head(p), Y_pred))
print(confusion_matrix(solution_df['Prediction'].head(p), Y_pred))

94.79
             precision    recall  f1-score   support

          0       0.98      0.15      0.26      7682
          1       0.53      1.00      0.69      7318

avg / total       0.76      0.56      0.47     15000

[[1146 6536]
 [  22 7296]]


In [18]:
perceptron = Perceptron()
perceptron.fit(X_train, Y_train)
Y_pred = perceptron.predict(X_test)
acc_perceptron = round(perceptron.score(X_train, Y_train) * 100, 2)
print acc_perceptron
print(classification_report(solution_df['Prediction'].head(p), Y_pred))
print(confusion_matrix(solution_df['Prediction'].head(p), Y_pred))

89.18
             precision    recall  f1-score   support

          0       0.95      0.15      0.26      7682
          1       0.53      0.99      0.69      7318

avg / total       0.74      0.56      0.47     15000

[[1150 6532]
 [  61 7257]]


In [19]:
gaussian = GaussianNB()
gaussian.fit(X_train, Y_train)
Y_pred = gaussian.predict(X_test)
acc_gaussian = round(gaussian.score(X_train, Y_train) * 100, 2)
print acc_gaussian
print(classification_report(solution_df['Prediction'].head(p), Y_pred))
print(confusion_matrix(solution_df['Prediction'].head(p), Y_pred))

93.22
             precision    recall  f1-score   support

          0       0.93      0.16      0.27      7682
          1       0.53      0.99      0.69      7318

avg / total       0.73      0.56      0.48     15000

[[1234 6448]
 [  99 7219]]


In [20]:
from sklearn.neural_network import MLPClassifier
#mlp = MLPClassifier(hidden_layer_sizes=(30,30,30))
mlp=MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(20,30,15), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
mlp.fit(X_train,Y_train)
Y_pred = mlp.predict(X_test)
acc_mlp = round(gaussian.score(X_train, Y_train) * 100, 2)
print acc_mlp
print(classification_report(solution_df['Prediction'].head(p), Y_pred))
print(confusion_matrix(solution_df['Prediction'].head(p), Y_pred))


93.22
             precision    recall  f1-score   support

          0       0.68      0.04      0.07      7682
          1       0.49      0.98      0.66      7318

avg / total       0.59      0.50      0.36     15000

[[ 283 7399]
 [ 132 7186]]


In [21]:
models = pd.DataFrame({
    'Model': ['Support Vector Machines', 'KNN', 'Logistic Regression', 
              'Random Forest', 'Naive Bayes', 'Perceptron', 
              'Stochastic Gradient Decent', 'Linear SVC', 
              'Decision Tree','MLP'],
    'Score': [acc_svc, acc_knn, acc_log, 
              acc_random_forest, acc_gaussian, acc_perceptron, 
              acc_sgd, acc_linear_svc, acc_decision_tree,acc_mlp]})
models.sort_values(by='Score', ascending=False)

Model   Score
3               Random Forest  100.00
8               Decision Tree  100.00
1                         KNN   97.94
0     Support Vector Machines   95.13
2         Logistic Regression   94.80
7                  Linear SVC   94.79
6  Stochastic Gradient Decent   94.27
4                 Naive Bayes   93.22
9                         MLP   93.22
5                  Perceptron   89.18

In [22]:
random_forest

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=100, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False)